FORMAT: 1A

# Majestic Thai

Majestic Thai is a simple API allowing patrons to view dishes available at the restaurant.

## Dishes Collection [/dishes]

### List All Dishes [GET]

+ Response 200 (application/json)

            
        [
            {"title": "Yellow Curry", "description": "Mild yellow curry, containing rich flavors of curry powder, coconut milk, potatoes, onions and carrots.", "price": "$10.50"},
            {"title": "Pad Thai", "description": "One of the most famous Thai rice noodles dish cooked with egg, bean spouts, tofu and sprinkled with ground peanut.", "price": "$10.50"},
            {"title": "Orange Chicken", "description": "Deep fried chicken sauteed in a tangy orange sauce.", "price": "$10.50"},
            {"title": "Duck Basil", "description": "Sliced boneless roasted duck, sauteed with bell peppers, green beans, onions and basil leaves, in a spicy homemade sauce.", "price": "$16.50"},
            {"title": "Fresh Spring Rolls (2 pcs.)", "description": "Spring roll sheets freshly wrapped with back tofu, carrots, lettuce, cucumbers, mint basil, and crystal thread noodles. They are served with peanut sauce.", "price": "$6.50"},
            {"title": "Rad Na", "description": "Stir fried rice noodle mixed black bean sauce, with choice of meat, broccoli, or Chinese broccoli, and homemade gravy sauce.", "price": "$10.50"},
            {"title": "Chow Mein", "description": "Stir fried with yellow rounded noodles with vegetables in home made sauce.", "price": "$10.50"},
            {"title": "Deep Fried Whole Fish", "description": "Deep fried whole fish (Golden Pompano) with your choice of spicy basil, three flavors, ginger or panag.", "price": "$16.50"},
            {"title": "Tom Kha Soup - Bowl", "description": "Coconut soup with your choice of chicken, tofu, vegetable, or shrimp for an additional charge. Served with mushrooms, onions, lime leaves, galangal and lime juice", "price": "$6.50"},
            {"title": "Prink-Khing", "description": "A special chili paste sauteed with green beans, bell peppers and Thai basil leaves.", "price": "$10.50"}

        ]

## Dish [/dishes/{dish_id}]

+ Parameters
    + dish_id (number) - ID of the Dish in the form of an integer

### View a Dish's Detail [GET]

+ Response 200 (application/json)

        {
            "title": "Yellow Curry", 
            "description": "Mild yellow curry, containing rich flavors of curry powder, coconut milk, potatoes, onions and carrots.", 
            "price": "$10.50"
        }
            
            
            
        
## Order Collection [/orders]

### List All Orders [GET]

+ Response 200 (application/json)

            
        [
            {"username": "Dan",
             "createdAt": "July 6, 2016, 12:15 p.m.",
             "total": "$27.50",
             "items":[
                     {"title": "Yellow Curry", "price": "$10.50"},
                     {"title": "Pad Thai", "price": "$10.50"},
                     {"title": "Fresh Spring Rolls (2 pcs.)", "price": "$6.50"}
                     ]
            },
            {"username": "Andy",
             "createdAt": "July 3, 2016, 6:35 p.m.",
             "total": "$37.50",
             "items":[
                     {"title": "Orange Chicken", "price": "$10.50"},
                     {"title": "Duck Basil", "price": "$16.50"},
                     {"title": "Rad Na", "price": "$10.50"}
                     ]
            },
            {"username": "Rob",
             "createdAt": "July 5, 2016, 1:45 p.m.",
             "total": "$44.00",
             "items":[
                     {"title": "Chow Mein", "price": "$10.50"},
                     {"title": "Deep Fried Whole Fish", "price": "$16.50"},
                     {"title": "Tom Kha Soup - Bowl", "price": "$6.50"},
                     {"title": "Prink-Khing", "price": "$10.50"}
                     ]
            }

        ]

## Order [/orders/{order_id}]

+ Parameters
    + order_id (number) - ID of the Order in the form of an integer

### View an Order's Detail [GET]

+ Response 200 (application/json)

            {"username": "Dan",
             "createdAt": "July 6, 2016, 12:15 p.m.",
             "total": "$27.50",
             "items":[
                     {"title": "Yellow Curry", "price": "$10.50"},
                     {"title": "Pad Thai", "price": "$10.50"},
                     {"title": "Fresh Spring Rolls (2 pcs.)", "price": "$6.50"}
                     ]
            }